[package]
name = "sim-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking"] }
bevy_prototype_lyon = { git = "https://github.com/Nilirad/bevy_prototype_lyon.git", branch = "v0.14-update" }
serde = "1.0.219"
serde_json = "1.0.142"

